### ISSUE TITLE
Cannot ping server when using Erlang 20.0.4 on Android 8 and above

### ISSUE THREAD

**Issue by D4no0** [JeromeDeBretagne/erlanglauncher#1]
Can you confirm that server is pingable using "facserver" mailbox? I managed to start the nodes, however I am unable to ping the server, the server runs without any errors, however since the hello_jinterface.beam is already compiled I cannot make much sense of it.

**Comment by D4no0** [comment]
I also can confirm that creating multiple nodes ping via Jinterface works without problems.

**Comment by JeromeDeBretagne** [comment]
Hey D4no0,
You can see the hello_jinterface.erl source [here](https://github.com/JeromeDeBretagne/erlanglauncher/blob/master/hello_jinterface.erl) that has been used to generate hello_jinterface.beam , the module is really small and simple.

**Comment by D4no0** [comment]
Thanks,
I managed to get the example going by using the jinterface provided with otp.

**Comment by JeromeDeBretagne** [comment]
Hey D4no0,

I've seen on the Erlang bug that you've succeeded by compiling and switching to a new Erlang 23rc3 version for arm64, congratulations !

I still have no idea why this existing sample code doesn't work anymore starting with Android 8 though.

Here is your repo for reference: 
https://github.com/D4no0/erlanglauncher

Cheers, 
Jérôme

**Comment by JeromeDeBretagne** [comment]
Thanks @D4no0 for your pointers, I've been able to fix this issue, by updating to version 23.0.2 for both the Erlang runtime and the Jinterface package, so the sample app should now be working fine up to Android 11 / Red Velvet Cake, started from commit daa07e7. I haven't been able to understand the root cause of the issue on Android 8 and above when using the older 20.x version of the Erlang runtime though .

I've taken this opportunity to add a 64-bit (arm64-v8a) version of the Erlang runtime, still based on release 23.0.2, in commit 3d026e1 in addition to the 32-bit (armeabi-v7a) one.
